const TABLE_FIELD_HEIGHT = 36;
const TABLE_HEADER_HEIGHT = 50;
const TABLE_COLOR_STRIP_HEIGHT = 7;
const CONNECTION_POINT_OFFSET_X = 15;
const CONNECTION_POINT_OFFSET_Y = 12;
const ARC_BASE_RADIUS = 10;
const LINE_EPSILON = 0.1;
const MIN_RADIUS = 2;
const RADIUS_DIVISOR = 3;
const DEFAULT_TABLE_WIDTH = 220;

export {
  TABLE_FIELD_HEIGHT,
  TABLE_HEADER_HEIGHT,
  TABLE_COLOR_STRIP_HEIGHT,
  CONNECTION_POINT_OFFSET_X,
  CONNECTION_POINT_OFFSET_Y,
  ARC_BASE_RADIUS,
  LINE_EPSILON,
  MIN_RADIUS,
  RADIUS_DIVISOR,
  DEFAULT_TABLE_WIDTH,
};
