const TABLE_FIELD_HEIGHT = 36;
const TABLE_HEADER_HEIGHT = 50;
const TABLE_COLOR_STRIP_HEIGHT = 7;
const CONNECTION_POINT_OFFSET_X = 15;
const CONNECTION_POINT_OFFSET_Y = 12;
const ARC_BASE_RADIUS = 10;
const LINE_EPSILON = 0.1;
const MIN_RADIUS = 2;
const RADIUS_DIVISOR = 3;
const DEFAULT_TABLE_WIDTH = 220;
const ZOOM_FACTOR = 1.05;
const ZOOM_EAGERNESS_FACTOR = 0.05;
const TRANSFORM_DEBOUNCE_DELAY = 16; // ~60fps
const DEFAULT_BLUE = "#155dfc";
const HEX_R_START = 1,
  HEX_R_END = 3; // R位置
const HEX_G_START = 3,
  HEX_G_END = 5; // G位置
const HEX_B_START = 5,
  HEX_B_END = 7; // B位置
const HEX_LENGTH = 7; // #RRGGBB
export {
  DEFAULT_BLUE,
  HEX_LENGTH,
  HEX_R_START,
  HEX_R_END,
  HEX_G_START,
  HEX_G_END,
  HEX_B_START,
  HEX_B_END,
  TABLE_FIELD_HEIGHT,
  TABLE_HEADER_HEIGHT,
  TABLE_COLOR_STRIP_HEIGHT,
  CONNECTION_POINT_OFFSET_X,
  CONNECTION_POINT_OFFSET_Y,
  ARC_BASE_RADIUS,
  LINE_EPSILON,
  MIN_RADIUS,
  RADIUS_DIVISOR,
  DEFAULT_TABLE_WIDTH,
  ZOOM_FACTOR,
  ZOOM_EAGERNESS_FACTOR,
  TRANSFORM_DEBOUNCE_DELAY,
};
